### ISSUE TITLE
Nuget package?

### ISSUE THREAD

**Issue by douglasg14b** [RichardVasquez/h3net#19]
Usage via a package manager would be a nice QoL addition.

The setup is pretty easy, setup package info & build output in the `.csproj`, version it, and upload it to nuget.org.

___________________________________________________________

If you want I can setup the `.csproj` & build output and make a PR, though the actual upload to nuget has to be done by you.

**Comment by RichardVasquez** [comment]
Sorry for very late delay in responding.  There's been a nuget package for almost a year now at https://www.nuget.org/packages/H3Lib/

I'll try to take a look at the PR after Advent of Code is over this year.

**Comment by douglasg14b** [comment]
@RichardVasquez The lib has naming conflicts with others namely `H3Lib` as bindings libs rely on a built version of the C library, and expect that build to be `H3Lib.dll` and this project `Name H3Net` provides `H3Lib.dll`... Creating a naming conflict.
