### ISSUE TITLE
GeoJSON

### ISSUE THREAD

**Issue by bluee** [RichardVasquez/h3net#23]
What's the recommended way to load geojson files into h3net?

**Comment by RichardVasquez** [comment]
I'm not sure I understand the question.

If you're talking about using h3net for polyfilling a geographical space, extract the geographic coordinates of the shape in order, then feed that into the polyfill function.

Some further detail would be helpful.

**Comment by bluee** [comment]
Hi @RichardVasquez 
Sorry for not being clear enough and first of all thanks for a great library!

What I have been trying to do is to take a .geojson file of a city outline and polyfill this to find out which H3 it's covered by. 
The challenge has been importing it into h3net. I have tried GeoMultiPolygon, GeoBoundary, LinkedGeoPolygon but not sure which one to use.

**Comment by RichardVasquez** [comment]
Hi @bluee 

Ok, let me see if I understand.  This is an example I did a while back.  It's a KML overlay placed on a section of San Jose, CA.

![image](https://user-images.githubusercontent.com/1706965/167980996-66180bf0-890f-41a5-8590-c25cb0f210d9.png)

I found the h3 cells that fit within the polygon at two different resolutions.

![image](https://user-images.githubusercontent.com/1706965/167981130-24973eba-c4d6-46ba-9d1e-0206ebd30e2c.png)
![image](https://user-images.githubusercontent.com/1706965/167981179-0d31b2cd-b1d3-4ce2-818c-d841616a4c3b.png)

If that's what you're talking about, I might be able to point you in the right direction.

![image](https://user-images.githubusercontent.com/1706965/167981291-ac2c6494-809f-449d-94e9-438087877a2b.png)

First off, the array of decimal values are the longitude and latitude pairs for each vertex of the red overlay.  Those values are in degree form as that's what my KML test provided.

Here's the thing though, the library uses radians.  I've provided an extension to turn degress to radians, and I create a new List<GeoCoord> with the vertices.  This list of GeoCoords is turned into a GeoFence object.  A GeoFence represents a section of space defined by the lines connecting the vertices.  Ensure the shape is closed (the original array repeats the same point at the beginning and end of the vertex list)

From there, the GeoFence is convereted to a GeoPolygon with the GeoFence representing the outer edge, along with additional GeoFence (in this case, zero) objects representing hols within the original polygon.

A lot of work, I'll admit, but if you notice, it's only a few lines to get the variable named _polys_.

Now that you have a GeoPolygon, you can polyfill it with H3 cells at the desired resolution.  In this case, I did it one time with resolution 11.

The rest of the code was some helper code that created KML files that I could import into Google Earth.

<hr>
If that's *not* what you meant, please point out where I misunderstood you, and I'll try again.

**Comment by bluee** [comment]
That was very helpful. Thank you **very** much!
